#!/bin/bash
source /etc/profile
the_path=`realpath $0`
gxg_root=`dirname "$the_path"`
cd $gxg_root
if [ "$1" == "start" ]
then
    /bin/stty --file=/dev/pts/0
    sudo -u www-data ./server start --quiet
fi
if [ "$1" == "stop" ]
then
    sudo -u www-data ./server stop
fi
exit 0
